# Generated by Django 4.1.5 on 2023-01-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGptQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('prompt', models.TextField()),
                ('tags', models.JSONField(default=dict)),
                ('response', models.TextField()),
                ('temperature', models.FloatField(default=0.5)),
                ('max_tokens', models.IntegerField(default=20)),
                ('top_p', models.FloatField(default=1)),
                ('n', models.IntegerField(default=1)),
                ('stream', models.BooleanField(default=False)),
                ('logprobs', models.IntegerField(default=None)),
                ('stop', models.CharField(default=None, max_length=1)),
            ],
        ),
    ]
