# Generated by Django 4.1.5 on 2023-01-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptquery',
            name='logprobs',
            field=models.IntegerField(default=0),
        ),
    ]
