# Generated by Django 4.1.5 on 2023-01-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_chatgptquery_logprobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptquery',
            name='stop',
            field=models.CharField(default='', max_length=1),
        ),
    ]
