# Generated by Django 4.1.5 on 2023-01-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0004_member_slug_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug_hash',
            field=models.CharField(default='<functio', max_length=8),
        ),
    ]
