# Generated by Django 4.1.5 on 2023-01-16 11:37

from django.db import migrations, models
import hello_world_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0005_alter_member_slug_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug_hash',
            field=models.CharField(default=hello_world_app.models.generate_slug_hash, max_length=8),
        ),
    ]
