# Generated by Django 4.1.5 on 2023-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('species', models.CharField(max_length=50, verbose_name='Especie')),
                ('sound', models.CharField(max_length=50, verbose_name='Sonido')),
            ],
        ),
    ]
