# Generated by Django 4.1.5 on 2023-01-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_views', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10, verbose_name='Frase destacada')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('headshot', models.ImageField(upload_to='author_headshots', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('city', models.CharField(max_length=60, verbose_name='Ciudad')),
                ('state_province', models.CharField(max_length=30, verbose_name='Provincia')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('website', models.URLField(verbose_name='Sitio web')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('authors', models.ManyToManyField(to='class_views.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_views.publisher')),
            ],
        ),
    ]
