# Generated by Django 4.1.5 on 2023-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_views', '0002_author_publisher_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='salutation',
            field=models.CharField(max_length=10, verbose_name='Sr/Sra'),
        ),
    ]
